extends Node

@warning_ignore("unused_signal")
signal action_queued(jobName)
@warning_ignore("unused_signal")
signal action_played(jobName)
@warning_ignore("unused_signal")
signal action_started(jobName)
@warning_ignore("unused_signal")
signal action_finished(jobName)
@warning_ignore("unused_signal")
signal craft_started(craftName)
@warning_ignore("unused_signal")
signal craft_finished(craftName)
@warning_ignore("unused_signal")
signal dungeon_started(craftName)
@warning_ignore("unused_signal")
signal dungeon_finished(craftName)
@warning_ignore("unused_signal")
signal queue_increased(jobName)
@warning_ignore("unused_signal")
signal queue_increased_back(jobName)
@warning_ignore("unused_signal")
signal queue_decreased(jobName)
@warning_ignore("unused_signal")
signal job_removed(jobName)
@warning_ignore("unused_signal")
signal inventory_increased(item)
@warning_ignore("unused_signal")
signal inventory_decreased(item)
